apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank
  namespace: idt
spec:
  selector:
    matchLabels:
      app: bank
  replicas: 4 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: bank
    spec:
      containers:
      - name: bank
        image: docker.io/shineset/idt:5596
        env:
        - name: TZ
          value: "ASIA/YEREVAN"
        ports:
        - containerPort: 9008

---
apiVersion: v1
kind: Service
metadata:
  name: bank
  namespace: idt
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 9008
      protocol: TCP
      nodePort: 30005
  selector:
    app: bank
